// DocumentViewerModal — Phase 4
// Displays a generated legal document with preview paywall, TTS pre-verification,
// download verification checklist, and PDF export via print window.

import React, { useState, useEffect, useRef } from "react";
import {
  X, Lock, Unlock, Volume2, Download, Check, Loader2,
  Pause, Play, Square, AlertCircle,
} from "lucide-react";
import { aiApi, ServerGeneratedDoc } from "../lib/aiApi";

const ORANGE = "#d9711f";
const PREVIEW_WORD_COUNT = 150;

function truncateWords(text: string, n: number): string {
  const words = text.split(/\s+/);
  if (words.length <= n) return text;
  return words.slice(0, n).join(" ");
}

function printDocumentAsPDF(title: string, content: string) {
  const lines = content.split("\n");
  const htmlContent = lines
    .map(l => {
      const t = l.trim();
      if (!t) return '<div style="margin:6px 0">&nbsp;</div>';
      // All-caps short lines are likely section headers
      if (t === t.toUpperCase() && t.length < 80 && t.length > 2) {
        return `<h3 style="margin:18px 0 4px;font-size:12pt">${t.replace(/</g, "&lt;")}</h3>`;
      }
      return `<p style="margin:3px 0">${t.replace(/</g, "&lt;").replace(/>/g, "&gt;")}</p>`;
    })
    .join("");

  const w = window.open("", "_blank", "width=794,height=700");
  if (!w) { alert("Enable pop-ups to download the PDF."); return; }
  w.document.write(`<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>${title.replace(/</g, "&lt;")}</title>
<style>
  body{font-family:"Times New Roman",serif;font-size:12pt;line-height:1.8;margin:1in;color:#000}
  h1{font-size:16pt;text-align:center;margin-bottom:24px;border-bottom:2px solid #000;padding-bottom:12px}
  h3{font-size:12pt;font-weight:bold;text-decoration:underline}
  p{margin:3px 0}
  .footer{text-align:center;color:#777;font-size:9pt;margin-top:40px;border-top:1px solid #ccc;padding-top:10px}
  @media print{body{margin:.75in}@page{margin:.75in}}
</style>
</head><body>
<h1>${title.replace(/</g, "&lt;")}</h1>
${htmlContent}
<div class="footer">Generated by HyperLaw AI Legal Assistant &bull; AI-generated content &bull; Not legal advice &bull; Review carefully before filing</div>
</body></html>`);
  w.document.close();
  setTimeout(() => { w.print(); }, 700);
}

function downloadAsText(doc: ServerGeneratedDoc) {
  const blob = new Blob([doc.content], { type: "text/plain" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${doc.title.replace(/[^a-z0-9]/gi, "_")}.txt`;
  a.click();
  URL.revokeObjectURL(url);
}

// ── Checklist items ────────────────────────────────────────────────────────────

interface CheckItem { id: string; text: string; checked: boolean }

const CHECKLIST_ITEMS: Omit<CheckItem, "checked">[] = [
  { id: "c1", text: "I have reviewed this document in its entirety" },
  { id: "c2", text: "I understand this document was generated by AI and may contain errors" },
  { id: "c3", text: "I will verify all facts, names, dates, and legal citations before filing" },
  { id: "c4", text: "I understand this is self-help content, not advice from a licensed attorney" },
];

// ── WaveBar — animated waveform bar ───────────────────────────────────────────

function WaveBar({ index, active }: { index: number; active: boolean }) {
  const animKey = `waveBar${index % 5}`;
  const baseHeight = 15 + (index % 7) * 8;
  return (
    <div style={{
      width: 4, borderRadius: 2, flexShrink: 0,
      background: active ? ORANGE : "#2a2a2a",
      height: active ? undefined : `${baseHeight}%`,
      animation: active ? `${animKey} ${0.35 + (index % 5) * 0.07}s ease-in-out infinite alternate` : "none",
      transition: "background 0.3s, height 0.3s",
    }} />
  );
}

// ── Main component ────────────────────────────────────────────────────────────

interface DocumentViewerModalProps {
  doc: ServerGeneratedDoc;
  creditBalance?: number;
  onBuyCredits?: () => void;
  onClose: () => void;
  /** Called when unlock succeeds — provides the updated doc (paymentStatus: "paid") */
  onDocUnlocked?: (updatedDoc: ServerGeneratedDoc) => void;
  /** Admin accounts bypass the paywall and are never charged */
  isAdmin?: boolean;
}

type FooterPanel = "actions" | "tts" | "checklist";

export default function DocumentViewerModal({
  doc, creditBalance, onBuyCredits, onClose, onDocUnlocked, isAdmin,
}: DocumentViewerModalProps) {
  // Admins always see full content — treat any doc as paid for UI purposes
  const isPaid = doc.paymentStatus === "paid" || !!isAdmin;

  // Unlock state
  const [unlocking, setUnlocking] = useState(false);
  const [unlockError, setUnlockError] = useState<string | null>(null);

  // Footer panel
  const [footerPanel, setFooterPanel] = useState<FooterPanel>("actions");

  // TTS state
  const [ttsPlaying, setTtsPlaying] = useState(false);
  const [ttsPaused, setTtsPaused] = useState(false);
  const [ttsReviewed, setTtsReviewed] = useState(false);
  const utteranceRef = useRef<SpeechSynthesisUtterance | null>(null);

  // Download checklist
  const [checklist, setChecklist] = useState<CheckItem[]>(
    CHECKLIST_ITEMS.map(c => ({ ...c, checked: false })),
  );
  const allChecked = checklist.every(c => c.checked);

  // Esc key closes modal
  useEffect(() => {
    const handler = (e: KeyboardEvent) => {
      if (e.key === "Escape") { stopTts(); onClose(); }
    };
    document.addEventListener("keydown", handler);
    return () => {
      document.removeEventListener("keydown", handler);
      stopTts();
    };
  }, []); // eslint-disable-line react-hooks/exhaustive-deps

  // ── TTS helpers ─────────────────────────────────────────────────────────────

  function startTts() {
    window.speechSynthesis.cancel();
    const u = new SpeechSynthesisUtterance(doc.content);
    u.rate = 0.9; u.pitch = 1;
    u.onend = () => { setTtsPlaying(false); setTtsPaused(false); setTtsReviewed(true); };
    u.onerror = () => { setTtsPlaying(false); setTtsPaused(false); };
    utteranceRef.current = u;
    window.speechSynthesis.speak(u);
    setTtsPlaying(true);
    setTtsPaused(false);
  }

  function pauseTts() {
    window.speechSynthesis.pause();
    setTtsPlaying(false);
    setTtsPaused(true);
  }

  function resumeTts() {
    window.speechSynthesis.resume();
    setTtsPlaying(true);
    setTtsPaused(false);
  }

  function stopTts() {
    window.speechSynthesis.cancel();
    setTtsPlaying(false);
    setTtsPaused(false);
    utteranceRef.current = null;
  }

  // ── Auto-unlock for admin ────────────────────────────────────────────────────
  // If admin opens a doc that's still in "preview" state in the DB, silently
  // flip it to "paid" on the server so future reads also return full content.
  useEffect(() => {
    if (isAdmin && doc.paymentStatus === "preview") {
      aiApi.generatedDocs.unlock(doc.id)
        .then(updated => onDocUnlocked?.(updated))
        .catch(() => { /* no-op — server may already have updated */ });
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // ── Unlock ───────────────────────────────────────────────────────────────────

  async function handleUnlock() {
    setUnlocking(true);
    setUnlockError(null);
    try {
      const updated = await aiApi.generatedDocs.unlock(doc.id);
      onDocUnlocked?.(updated);
    } catch (err: unknown) {
      const e = err as { message?: string; code?: string };
      if (e.code === "insufficient_credits") {
        onClose();
        onBuyCredits?.();
      } else {
        setUnlockError(e.message || "Unlock failed. Please try again.");
      }
    } finally {
      setUnlocking(false);
    }
  }

  const previewText = truncateWords(doc.content, PREVIEW_WORD_COUNT);
  const docTypeLabel = doc.documentType.replace(/_/g, " ").toUpperCase();
  const hasCredits = (creditBalance ?? 0) > 0;

  return (
    <div
      onClick={e => { if (e.target === e.currentTarget) { stopTts(); onClose(); } }}
      style={{
        position: "fixed", inset: 0, zIndex: 1100,
        background: "rgba(0,0,0,0.88)",
        display: "flex", alignItems: "center", justifyContent: "center",
        padding: 16,
      }}
    >
      <div style={{
        background: "#0d0d0d", border: "1px solid #222",
        borderRadius: 16, width: "100%", maxWidth: 660, maxHeight: "92vh",
        display: "flex", flexDirection: "column",
        boxShadow: "0 40px 80px rgba(0,0,0,0.9)",
        overflow: "hidden",
      }}>

        {/* ── Header ─────────────────────────────────────────────────────── */}
        <div style={{
          display: "flex", alignItems: "flex-start", gap: 10,
          padding: "14px 16px", borderBottom: "1px solid #1a1a1a", flexShrink: 0,
        }}>
          <div style={{ flex: 1, minWidth: 0 }}>
            <div style={{ fontWeight: 800, fontSize: 15, color: "#eee", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>
              {doc.title}
            </div>
            <div style={{ display: "flex", alignItems: "center", gap: 6, marginTop: 5 }}>
              <span style={{ fontSize: 10, fontWeight: 700, color: "#444", background: "#1a1a1a", borderRadius: 4, padding: "2px 6px" }}>
                {docTypeLabel}
              </span>
              {isAdmin ? (
                <span style={{ fontSize: 10, fontWeight: 700, color: ORANGE, display: "flex", alignItems: "center", gap: 3 }}>
                  ADMIN ACCESS
                </span>
              ) : isPaid ? (
                <span style={{ fontSize: 10, fontWeight: 700, color: "#22c55e", display: "flex", alignItems: "center", gap: 3 }}>
                  <Check size={10} /> UNLOCKED
                </span>
              ) : (
                <span style={{ fontSize: 10, fontWeight: 700, color: ORANGE, display: "flex", alignItems: "center", gap: 3 }}>
                  <Lock size={10} /> PREVIEW
                </span>
              )}
              <span style={{ fontSize: 10, color: "#444" }}>
                {new Date(doc.createdAt).toLocaleDateString()}
              </span>
            </div>
          </div>
          <button
            onClick={() => { stopTts(); onClose(); }}
            style={{ background: "none", border: "none", cursor: "pointer", color: "#555", padding: 4, flexShrink: 0 }}
          >
            <X size={18} />
          </button>
        </div>

        {/* ── Document content ───────────────────────────────────────────── */}
        <div style={{ flex: 1, overflowY: "auto", position: "relative", minHeight: 0 }}>

          {/* Preview — truncated with fade */}
          {!isPaid && (
            <div style={{ position: "relative" }}>
              <div style={{
                padding: "20px 20px 0", color: "#bbb", fontSize: 13, lineHeight: 1.85,
                whiteSpace: "pre-wrap", wordBreak: "break-word",
              }}>
                {previewText}
                <span style={{ color: "#555" }}> …</span>
              </div>
              <div style={{
                position: "sticky", bottom: 0, left: 0, right: 0, height: 120,
                background: "linear-gradient(to bottom, transparent 0%, #0d0d0d 75%)",
                pointerEvents: "none",
              }} />
            </div>
          )}

          {/* Paid — full content */}
          {isPaid && (
            <div style={{ padding: "20px 20px 8px" }}>
              <div style={{
                color: "#c8c8c8", fontSize: 13, lineHeight: 1.85,
                whiteSpace: "pre-wrap", wordBreak: "break-word",
              }}>
                {doc.content}
              </div>
              <div style={{
                marginTop: 24, padding: "12px 14px",
                background: "#0a0a0a", borderRadius: 10,
                border: "1px solid #1a1a1a",
                fontSize: 11, color: "#444", lineHeight: 1.55,
              }}>
                <AlertCircle size={11} color="#555" style={{ display: "inline", marginRight: 5, verticalAlign: "middle" }} />
                AI-generated content — not legal advice. Verify all facts, dates, case numbers, and citations before filing. Consult a licensed attorney for your specific situation.
              </div>
            </div>
          )}
        </div>

        {/* ── Footer ─────────────────────────────────────────────────────── */}
        <div style={{ borderTop: "1px solid #1a1a1a", padding: "14px 16px", flexShrink: 0 }}>

          {/* Preview paywall */}
          {!isPaid && (
            <div style={{ display: "flex", flexDirection: "column", gap: 10 }}>
              <div style={{ fontSize: 12, color: "#555", lineHeight: 1.55 }}>
                Verify the formatting above matches your case, then unlock the full document. Unlocking permanently saves the complete document to your case with read-aloud review and PDF download.
              </div>
              {unlockError && (
                <div style={{ fontSize: 12, color: "#ef4444", background: "#1a0d0d", border: "1px solid #3a1a1a", borderRadius: 8, padding: "7px 10px" }}>
                  {unlockError}
                </div>
              )}
              <button
                onClick={handleUnlock}
                disabled={unlocking}
                style={{
                  background: ORANGE, border: "none", borderRadius: 10,
                  padding: "12px 16px", color: "#fff", fontWeight: 800, fontSize: 14,
                  cursor: unlocking ? "not-allowed" : "pointer",
                  display: "flex", alignItems: "center", justifyContent: "center", gap: 8,
                  opacity: unlocking ? 0.7 : 1,
                }}
              >
                {unlocking
                  ? <Loader2 size={15} style={{ animation: "spin 1s linear infinite" }} />
                  : <Unlock size={15} />}
                {unlocking ? "Unlocking…" : "Unlock Full Document  (1 credit)"}
              </button>
              {!hasCredits && (
                <button
                  onClick={() => { onClose(); onBuyCredits?.(); }}
                  style={{
                    background: "none", border: "1px solid #2a2a2a", borderRadius: 8,
                    padding: "8px 12px", color: "#aaa", fontSize: 12, cursor: "pointer",
                  }}
                >
                  + Buy Credits
                </button>
              )}
              {creditBalance !== undefined && (
                <div style={{ fontSize: 11, color: hasCredits ? "#555" : "#ef4444", textAlign: "center" }}>
                  {creditBalance} credit{creditBalance !== 1 ? "s" : ""} available
                </div>
              )}
            </div>
          )}

          {/* Paid — action bar */}
          {isPaid && footerPanel === "actions" && (
            <div style={{ display: "flex", gap: 8 }}>
              <button
                onClick={() => { setFooterPanel("tts"); }}
                style={{
                  flex: 1, background: "#111", border: "1px solid #2a2a2a",
                  borderRadius: 10, padding: "10px 14px", color: "#bbb",
                  fontSize: 12, fontWeight: 700, cursor: "pointer",
                  display: "flex", alignItems: "center", justifyContent: "center", gap: 6,
                }}
              >
                <Volume2 size={14} color={ORANGE} /> Verify with Read-Aloud
              </button>
              <button
                onClick={() => setFooterPanel("checklist")}
                style={{
                  flex: 1, background: "#111", border: "1px solid #2a2a2a",
                  borderRadius: 10, padding: "10px 14px", color: "#bbb",
                  fontSize: 12, fontWeight: 700, cursor: "pointer",
                  display: "flex", alignItems: "center", justifyContent: "center", gap: 6,
                }}
              >
                <Download size={14} color="#555" /> Download PDF
              </button>
            </div>
          )}

          {/* Paid — TTS Pre-Verification */}
          {isPaid && footerPanel === "tts" && (
            <div style={{ display: "flex", flexDirection: "column", gap: 10 }}>
              <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between" }}>
                <div style={{ fontSize: 11, color: "#555", fontWeight: 700, letterSpacing: 0.5 }}>PRE-VERIFICATION READER</div>
                <button onClick={() => { stopTts(); setFooterPanel("actions"); }}
                  style={{ background: "none", border: "none", cursor: "pointer", color: "#555", padding: 4 }}>
                  <X size={14} />
                </button>
              </div>

              {/* Waveform */}
              <div style={{
                display: "flex", alignItems: "flex-end", gap: 3, height: 36,
                justifyContent: "center", background: "#0a0a0a",
                borderRadius: 8, padding: "6px 12px",
              }}>
                {Array.from({ length: 22 }).map((_, i) => (
                  <WaveBar key={i} index={i} active={ttsPlaying} />
                ))}
              </div>

              {/* Controls */}
              <div style={{ display: "flex", gap: 6 }}>
                {!ttsPlaying && !ttsPaused && (
                  <button onClick={startTts} style={{
                    flex: 1, background: ORANGE, border: "none", borderRadius: 8,
                    padding: "9px 12px", color: "#fff", fontWeight: 700, fontSize: 12,
                    cursor: "pointer", display: "flex", alignItems: "center", justifyContent: "center", gap: 5,
                  }}>
                    <Play size={13} /> Start Reading
                  </button>
                )}
                {ttsPlaying && (
                  <button onClick={pauseTts} style={{
                    flex: 1, background: "#111", border: `1px solid ${ORANGE}`, borderRadius: 8,
                    padding: "9px 12px", color: ORANGE, fontWeight: 700, fontSize: 12,
                    cursor: "pointer", display: "flex", alignItems: "center", justifyContent: "center", gap: 5,
                  }}>
                    <Pause size={13} /> Pause
                  </button>
                )}
                {ttsPaused && (
                  <button onClick={resumeTts} style={{
                    flex: 1, background: "#111", border: `1px solid ${ORANGE}`, borderRadius: 8,
                    padding: "9px 12px", color: ORANGE, fontWeight: 700, fontSize: 12,
                    cursor: "pointer", display: "flex", alignItems: "center", justifyContent: "center", gap: 5,
                  }}>
                    <Play size={13} /> Resume
                  </button>
                )}
                {(ttsPlaying || ttsPaused) && (
                  <button onClick={stopTts} style={{
                    background: "#111", border: "1px solid #2a2a2a", borderRadius: 8,
                    padding: "9px 12px", color: "#555", fontSize: 12, cursor: "pointer",
                    display: "flex", alignItems: "center", gap: 5,
                  }}>
                    <Square size={13} /> Stop
                  </button>
                )}
              </div>

              <div style={{ fontSize: 11, color: "#555", lineHeight: 1.5 }}>
                ⚠️ AI can make mistakes. Listen carefully and verify every detail before relying on this document.
              </div>

              <label style={{ display: "flex", alignItems: "flex-start", gap: 8, cursor: "pointer" }}>
                <input type="checkbox" checked={ttsReviewed}
                  onChange={e => setTtsReviewed(e.target.checked)}
                  style={{ marginTop: 2, accentColor: ORANGE, flexShrink: 0 }} />
                <span style={{ fontSize: 12, color: "#aaa", lineHeight: 1.4 }}>
                  I have carefully reviewed this document and understand it is AI-generated
                </span>
              </label>

              {ttsReviewed && (
                <button
                  onClick={() => { stopTts(); setFooterPanel("checklist"); }}
                  style={{
                    background: ORANGE, border: "none", borderRadius: 8,
                    padding: "9px 14px", color: "#fff", fontWeight: 800, fontSize: 12,
                    cursor: "pointer", display: "flex", alignItems: "center", justifyContent: "center", gap: 5,
                  }}
                >
                  <Download size={13} /> Continue to Download
                </button>
              )}
            </div>
          )}

          {/* Paid — Download verification checklist */}
          {isPaid && footerPanel === "checklist" && (
            <div style={{ display: "flex", flexDirection: "column", gap: 10 }}>
              <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between" }}>
                <div style={{ fontSize: 11, color: "#555", fontWeight: 700, letterSpacing: 0.5 }}>BEFORE YOU DOWNLOAD</div>
                <button onClick={() => setFooterPanel("actions")}
                  style={{ background: "none", border: "none", cursor: "pointer", color: "#555", padding: 4 }}>
                  <X size={14} />
                </button>
              </div>
              <div style={{ display: "flex", flexDirection: "column", gap: 7 }}>
                {checklist.map(item => (
                  <label key={item.id} style={{ display: "flex", alignItems: "flex-start", gap: 8, cursor: "pointer" }}>
                    <input
                      type="checkbox"
                      checked={item.checked}
                      onChange={() => setChecklist(prev =>
                        prev.map(c => c.id === item.id ? { ...c, checked: !c.checked } : c)
                      )}
                      style={{ marginTop: 3, accentColor: ORANGE, flexShrink: 0 }}
                    />
                    <span style={{ fontSize: 12, color: "#aaa", lineHeight: 1.4 }}>{item.text}</span>
                  </label>
                ))}
              </div>
              <div style={{ display: "flex", gap: 8 }}>
                <button
                  disabled={!allChecked}
                  onClick={() => {
                    if (!allChecked) return;
                    printDocumentAsPDF(doc.title, doc.content);
                    setFooterPanel("actions");
                  }}
                  style={{
                    flex: 1,
                    background: allChecked ? ORANGE : "#1a1a1a",
                    border: "none", borderRadius: 8,
                    padding: "9px 14px",
                    color: allChecked ? "#fff" : "#444",
                    fontWeight: 800, fontSize: 12,
                    cursor: allChecked ? "pointer" : "not-allowed",
                    display: "flex", alignItems: "center", justifyContent: "center", gap: 5,
                    transition: "background 0.2s",
                  }}
                >
                  <Download size={13} /> Download PDF
                </button>
                <button
                  onClick={() => downloadAsText(doc)}
                  style={{
                    background: "#111", border: "1px solid #2a2a2a",
                    borderRadius: 8, padding: "9px 12px",
                    color: "#666", fontSize: 12, cursor: "pointer",
                    display: "flex", alignItems: "center", gap: 5,
                  }}
                >
                  .TXT
                </button>
              </div>
              {!allChecked && (
                <div style={{ fontSize: 11, color: "#555", textAlign: "center" }}>
                  Please confirm all items above to enable download.
                </div>
              )}
            </div>
          )}
        </div>
      </div>

      {/* Waveform keyframe animations */}
      <style>{`
        @keyframes waveBar0 { 0%{height:15%} 100%{height:85%} }
        @keyframes waveBar1 { 0%{height:35%} 100%{height:65%} }
        @keyframes waveBar2 { 0%{height:20%} 100%{height:100%} }
        @keyframes waveBar3 { 0%{height:55%} 100%{height:35%} }
        @keyframes waveBar4 { 0%{height:28%} 100%{height:75%} }
      `}</style>
    </div>
  );
}
