// DocumentViewerModal
// Displays a generated legal document in full (usage-based billing — no paywall),
// with TTS pre-verification, a download verification checklist, and PDF export.

import React, { useState, useEffect, useRef } from "react";
import { COMPLIANCE, VERIFICATION_CHECKLIST } from "../lib/compliance";
import {
  X, Volume2, Download, Check, Loader2,
  Pause, Play, Square, AlertCircle,
} from "lucide-react";
import { aiApi, ServerGeneratedDoc } from "../lib/aiApi";

const ORANGE = "#d9711f";

function printDocumentAsPDF(title: string, content: string) {
  const lines = content.split("\n");
  const htmlContent = lines
    .map(l => {
      const t = l.trim();
      if (!t) return '<div style="margin:6px 0">&nbsp;</div>';
      // All-caps short lines are likely section headers
      if (t === t.toUpperCase() && t.length < 80 && t.length > 2) {
        return `<h3 style="margin:18px 0 4px;font-size:12pt">${t.replace(/</g, "&lt;")}</h3>`;
      }
      return `<p style="margin:3px 0">${t.replace(/</g, "&lt;").replace(/>/g, "&gt;")}</p>`;
    })
    .join("");

  const w = window.open("", "_blank", "width=794,height=700");
  if (!w) { alert("Enable pop-ups to download the PDF."); return; }
  w.document.write(`<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>${title.replace(/</g, "&lt;")}</title>
<style>
  body{font-family:"Times New Roman",serif;font-size:12pt;line-height:1.8;margin:1in;color:#000}
  h1{font-size:16pt;text-align:center;margin-bottom:24px;border-bottom:2px solid #000;padding-bottom:12px}
  h3{font-size:12pt;font-weight:bold;text-decoration:underline}
  p{margin:3px 0}
  .footer{text-align:center;color:#777;font-size:9pt;margin-top:40px;border-top:1px solid #ccc;padding-top:10px}
  @media print{body{margin:.75in}@page{margin:.75in}}
</style>
</head><body>
<h1>${title.replace(/</g, "&lt;")}</h1>
${htmlContent}
<div class="footer">Generated by HyperLaw AI Legal Assistant &bull; ${COMPLIANCE.EXPORT_NOTICE}</div>
</body></html>`);
  w.document.close();
  setTimeout(() => { w.print(); }, 700);
}

function downloadAsText(doc: ServerGeneratedDoc) {
  const blob = new Blob([doc.content], { type: "text/plain" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${doc.title.replace(/[^a-z0-9]/gi, "_")}.txt`;
  a.click();
  URL.revokeObjectURL(url);
}

// ── Checklist items ────────────────────────────────────────────────────────────
// Sourced from compliance.ts — edit text there, updates here automatically.

interface CheckItem { id: string; text: string; checked: boolean }

// ── Word-by-word TTS highlight renderer ───────────────────────────────────────
// Splits content into word/whitespace tokens and applies an orange glow to the
// currently spoken word, identified by the SpeechSynthesisUtterance charIndex.
function renderHighlightedText(text: string, charIndex: number) {
  if (charIndex < 0) return <>{text}</>;
  const tokens = text.split(/(\s+)/);
  let offset = 0;
  return (
    <>
      {tokens.map((token, i) => {
        const start = offset;
        offset += token.length;
        const isWord = token.length > 0 && !/^\s+$/.test(token);
        const isActive = isWord && charIndex >= start && charIndex < offset;
        return (
          <span
            key={i}
            style={isActive ? {
              background: "rgba(217,113,31,0.22)",
              color: "#f97316",
              borderRadius: 3,
              textShadow: "0 0 10px rgba(217,113,31,0.55)",
              padding: "0 1px",
            } : undefined}
          >
            {token}
          </span>
        );
      })}
    </>
  );
}

// ── WaveBar — animated waveform bar ───────────────────────────────────────────

function WaveBar({ index, active }: { index: number; active: boolean }) {
  const animKey = `waveBar${index % 5}`;
  const baseHeight = 15 + (index % 7) * 8;
  return (
    <div
      aria-hidden="true"
      style={{
        width: 4, borderRadius: 2, flexShrink: 0,
        background: active ? ORANGE : "#2a2a2a",
        height: active ? undefined : `${baseHeight}%`,
        animation: active ? `${animKey} ${0.35 + (index % 5) * 0.07}s ease-in-out infinite alternate` : "none",
        transition: "background 0.3s, height 0.3s",
      }}
    />
  );
}

// ── Main component ────────────────────────────────────────────────────────────

interface DocumentViewerModalProps {
  doc: ServerGeneratedDoc;
  onClose: () => void;
}

type FooterPanel = "actions" | "tts" | "checklist";

export default function DocumentViewerModal({
  doc, onClose,
}: DocumentViewerModalProps) {
  // Footer panel
  const [footerPanel, setFooterPanel] = useState<FooterPanel>("actions");

  // TTS state
  const [ttsPlaying, setTtsPlaying] = useState(false);
  const [ttsPaused, setTtsPaused] = useState(false);
  const [ttsReviewed, setTtsReviewed] = useState(false);
  /** charIndex from SpeechSynthesisUtterance.onboundary — drives word-level highlight. -1 = inactive. */
  const [ttsCharIndex, setTtsCharIndex] = useState(-1);
  const utteranceRef = useRef<SpeechSynthesisUtterance | null>(null);

  // Download checklist
  const [checklist, setChecklist] = useState<CheckItem[]>(
    VERIFICATION_CHECKLIST.map(c => ({ ...c, checked: false })),
  );
  const allChecked = checklist.every(c => c.checked);

  // Esc key closes modal
  useEffect(() => {
    const handler = (e: KeyboardEvent) => {
      if (e.key === "Escape") { stopTts(); onClose(); }
    };
    document.addEventListener("keydown", handler);
    return () => {
      document.removeEventListener("keydown", handler);
      stopTts();
    };
  }, []); // eslint-disable-line react-hooks/exhaustive-deps

  // ── TTS helpers ─────────────────────────────────────────────────────────────

  function startTts() {
    window.speechSynthesis.cancel();
    const u = new SpeechSynthesisUtterance(doc.content);
    u.rate = 0.9; u.pitch = 1;
    // Word-by-word highlight: update on any boundary event since browsers vary —
    // Chrome emits name="word", Safari sometimes emits name="sentence" or omits it.
    u.onboundary = (e: SpeechSynthesisEvent) => {
      if (e.charIndex !== undefined) setTtsCharIndex(e.charIndex);
    };
    u.onend = () => { setTtsPlaying(false); setTtsPaused(false); setTtsReviewed(true); setTtsCharIndex(-1); };
    u.onerror = () => { setTtsPlaying(false); setTtsPaused(false); setTtsCharIndex(-1); };
    utteranceRef.current = u;
    window.speechSynthesis.speak(u);
    setTtsPlaying(true);
    setTtsPaused(false);
  }

  function pauseTts() {
    window.speechSynthesis.pause();
    setTtsPlaying(false);
    setTtsPaused(true);
  }

  function resumeTts() {
    window.speechSynthesis.resume();
    setTtsPlaying(true);
    setTtsPaused(false);
  }

  function stopTts() {
    window.speechSynthesis.cancel();
    setTtsPlaying(false);
    setTtsPaused(false);
    setTtsCharIndex(-1);
    utteranceRef.current = null;
  }

  const docTypeLabel = doc.documentType.replace(/_/g, " ").toUpperCase();

  return (
    <div
      onClick={e => { if (e.target === e.currentTarget) { stopTts(); onClose(); } }}
      style={{
        position: "fixed", inset: 0, zIndex: 1100,
        background: "rgba(0,0,0,0.88)",
        display: "flex", alignItems: "center", justifyContent: "center",
        padding: 16,
      }}
    >
      <div style={{
        background: "#0d0d0d", border: "1px solid #222",
        borderRadius: 16, width: "100%", maxWidth: 660, maxHeight: "92vh",
        display: "flex", flexDirection: "column",
        boxShadow: "0 40px 80px rgba(0,0,0,0.9)",
        overflow: "hidden",
      }}>

        {/* ── Header ─────────────────────────────────────────────────────── */}
        <div style={{
          display: "flex", alignItems: "flex-start", gap: 10,
          padding: "14px 16px", borderBottom: "1px solid #1a1a1a", flexShrink: 0,
        }}>
          <div style={{ flex: 1, minWidth: 0 }}>
            <div style={{ fontWeight: 800, fontSize: 15, color: "#eee", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>
              {doc.title}
            </div>
            <div style={{ display: "flex", alignItems: "center", gap: 6, marginTop: 5 }}>
              <span style={{ fontSize: 10, fontWeight: 700, color: "#444", background: "#1a1a1a", borderRadius: 4, padding: "2px 6px" }}>
                {docTypeLabel}
              </span>
              <span style={{ fontSize: 10, color: "#444" }}>
                {new Date(doc.createdAt).toLocaleDateString()}
              </span>
            </div>
          </div>
          <button
            aria-label="Close document"
            onClick={() => { stopTts(); onClose(); }}
            style={{ background: "none", border: "none", cursor: "pointer", color: "#555", padding: 4, flexShrink: 0 }}
          >
            <X size={18} />
          </button>
        </div>

        {/* ── Document content ───────────────────────────────────────────── */}
        <div style={{ flex: 1, overflowY: "auto", position: "relative", minHeight: 0 }}>

          {/* Full document content (usage-based billing — always shown) */}
          <div style={{ padding: "20px 20px 8px" }}>
              <div style={{
                color: "#c8c8c8", fontSize: 13, lineHeight: 1.85,
                whiteSpace: "pre-wrap", wordBreak: "break-word",
              }}>
                {(ttsPlaying || ttsPaused)
                  ? renderHighlightedText(doc.content, ttsCharIndex)
                  : doc.content}
              </div>
              <div style={{
                marginTop: 24, padding: "12px 14px",
                background: "#0a0a0a", borderRadius: 10,
                border: "1px solid #1a1a1a",
                fontSize: 11, color: "#444", lineHeight: 1.55,
              }}>
                <AlertCircle size={11} color="#555" style={{ display: "inline", marginRight: 5, verticalAlign: "middle" }} />
                {COMPLIANCE.AI_GENERATED_SHORT}
              </div>
            </div>
        </div>

        {/* ── Footer ─────────────────────────────────────────────────────── */}
        <div style={{ borderTop: "1px solid #1a1a1a", padding: "14px 16px", flexShrink: 0 }}>

          {/* Action bar */}
          {footerPanel === "actions" && (
            <div style={{ display: "flex", gap: 8 }}>
              <button
                onClick={() => { setFooterPanel("tts"); }}
                style={{
                  flex: 1, background: "#111", border: "1px solid #2a2a2a",
                  borderRadius: 10, padding: "10px 14px", color: "#bbb",
                  fontSize: 12, fontWeight: 700, cursor: "pointer",
                  display: "flex", alignItems: "center", justifyContent: "center", gap: 6,
                }}
              >
                <Volume2 size={14} color={ORANGE} /> Verify with Read-Aloud
              </button>
              <button
                onClick={() => setFooterPanel("checklist")}
                style={{
                  flex: 1, background: "#111", border: "1px solid #2a2a2a",
                  borderRadius: 10, padding: "10px 14px", color: "#bbb",
                  fontSize: 12, fontWeight: 700, cursor: "pointer",
                  display: "flex", alignItems: "center", justifyContent: "center", gap: 6,
                }}
              >
                <Download size={14} color="#555" /> Download PDF
              </button>
            </div>
          )}

          {/* Paid — TTS Pre-Verification */}
          {footerPanel === "tts" && (
            <div style={{ display: "flex", flexDirection: "column", gap: 10 }}>
              <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between" }}>
                <div style={{ fontSize: 11, color: "#555", fontWeight: 700, letterSpacing: 0.5 }}>PRE-VERIFICATION READER</div>
                <button onClick={() => { stopTts(); setFooterPanel("actions"); }}
                  style={{ background: "none", border: "none", cursor: "pointer", color: "#555", padding: 4 }}>
                  <X size={14} />
                </button>
              </div>

              {/* Waveform */}
              <div style={{
                display: "flex", alignItems: "flex-end", gap: 3, height: 36,
                justifyContent: "center", background: "#0a0a0a",
                borderRadius: 8, padding: "6px 12px",
              }}>
                {Array.from({ length: 22 }).map((_, i) => (
                  <WaveBar key={i} index={i} active={ttsPlaying} />
                ))}
              </div>

              {/* Controls */}
              <div style={{ display: "flex", gap: 6 }}>
                {!ttsPlaying && !ttsPaused && (
                  <button onClick={startTts} style={{
                    flex: 1, background: ORANGE, border: "none", borderRadius: 8,
                    padding: "9px 12px", color: "#fff", fontWeight: 700, fontSize: 12,
                    cursor: "pointer", display: "flex", alignItems: "center", justifyContent: "center", gap: 5,
                  }}>
                    <Play size={13} /> Start Reading
                  </button>
                )}
                {ttsPlaying && (
                  <button onClick={pauseTts} style={{
                    flex: 1, background: "#111", border: `1px solid ${ORANGE}`, borderRadius: 8,
                    padding: "9px 12px", color: ORANGE, fontWeight: 700, fontSize: 12,
                    cursor: "pointer", display: "flex", alignItems: "center", justifyContent: "center", gap: 5,
                  }}>
                    <Pause size={13} /> Pause
                  </button>
                )}
                {ttsPaused && (
                  <button onClick={resumeTts} style={{
                    flex: 1, background: "#111", border: `1px solid ${ORANGE}`, borderRadius: 8,
                    padding: "9px 12px", color: ORANGE, fontWeight: 700, fontSize: 12,
                    cursor: "pointer", display: "flex", alignItems: "center", justifyContent: "center", gap: 5,
                  }}>
                    <Play size={13} /> Resume
                  </button>
                )}
                {(ttsPlaying || ttsPaused) && (
                  <button onClick={stopTts} style={{
                    background: "#111", border: "1px solid #2a2a2a", borderRadius: 8,
                    padding: "9px 12px", color: "#555", fontSize: 12, cursor: "pointer",
                    display: "flex", alignItems: "center", gap: 5,
                  }}>
                    <Square size={13} /> Stop
                  </button>
                )}
              </div>

              <div style={{ fontSize: 11, color: "#555", lineHeight: 1.5 }}>
                {COMPLIANCE.TTS_WARNING}
              </div>

              <label style={{ display: "flex", alignItems: "flex-start", gap: 8, cursor: "pointer" }}>
                <input type="checkbox" checked={ttsReviewed}
                  onChange={e => setTtsReviewed(e.target.checked)}
                  style={{ marginTop: 2, accentColor: ORANGE, flexShrink: 0 }} />
                <span style={{ fontSize: 12, color: "#aaa", lineHeight: 1.4 }}>
                  {COMPLIANCE.TTS_REVIEW_ACKNOWLEDGMENT}
                </span>
              </label>

              {ttsReviewed && (
                <button
                  onClick={() => {
                    stopTts();
                    setFooterPanel("checklist");
                    // Record TTS verification server-side (fire-and-forget)
                    aiApi.generatedDocs.verify(doc.id).catch(() => {});
                  }}
                  style={{
                    background: ORANGE, border: "none", borderRadius: 8,
                    padding: "9px 14px", color: "#fff", fontWeight: 800, fontSize: 12,
                    cursor: "pointer", display: "flex", alignItems: "center", justifyContent: "center", gap: 5,
                  }}
                >
                  <Download size={13} /> Continue to Download
                </button>
              )}
            </div>
          )}

          {/* Paid — Download verification checklist */}
          {footerPanel === "checklist" && (
            <div style={{ display: "flex", flexDirection: "column", gap: 10 }}>
              <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between" }}>
                <div style={{ fontSize: 11, color: "#555", fontWeight: 700, letterSpacing: 0.5 }}>BEFORE YOU DOWNLOAD</div>
                <button onClick={() => setFooterPanel("actions")}
                  style={{ background: "none", border: "none", cursor: "pointer", color: "#555", padding: 4 }}>
                  <X size={14} />
                </button>
              </div>
              <div style={{ display: "flex", flexDirection: "column", gap: 7 }}>
                {checklist.map(item => (
                  <label key={item.id} style={{ display: "flex", alignItems: "flex-start", gap: 8, cursor: "pointer" }}>
                    <input
                      type="checkbox"
                      checked={item.checked}
                      onChange={() => setChecklist(prev =>
                        prev.map(c => c.id === item.id ? { ...c, checked: !c.checked } : c)
                      )}
                      style={{ marginTop: 3, accentColor: ORANGE, flexShrink: 0 }}
                    />
                    <span style={{ fontSize: 12, color: "#aaa", lineHeight: 1.4 }}>{item.text}</span>
                  </label>
                ))}
              </div>
              <div style={{ display: "flex", gap: 8 }}>
                <button
                  disabled={!allChecked}
                  onClick={() => {
                    if (!allChecked) return;
                    printDocumentAsPDF(doc.title, doc.content);
                    setFooterPanel("actions");
                  }}
                  style={{
                    flex: 1,
                    background: allChecked ? ORANGE : "#1a1a1a",
                    border: "none", borderRadius: 8,
                    padding: "9px 14px",
                    color: allChecked ? "#fff" : "#444",
                    fontWeight: 800, fontSize: 12,
                    cursor: allChecked ? "pointer" : "not-allowed",
                    display: "flex", alignItems: "center", justifyContent: "center", gap: 5,
                    transition: "background 0.2s",
                  }}
                >
                  <Download size={13} /> Download PDF
                </button>
                <button
                  disabled={!allChecked}
                  onClick={() => { if (allChecked) downloadAsText(doc); }}
                  style={{
                    background: allChecked ? "#111" : "#0a0a0a",
                    border: `1px solid ${allChecked ? "#2a2a2a" : "#1a1a1a"}`,
                    borderRadius: 8, padding: "9px 12px",
                    color: allChecked ? "#666" : "#2a2a2a",
                    fontSize: 12,
                    cursor: allChecked ? "pointer" : "not-allowed",
                    display: "flex", alignItems: "center", gap: 5,
                    transition: "background 0.2s, color 0.2s",
                  }}
                >
                  .TXT
                </button>
              </div>
              {!allChecked && (
                <div style={{ fontSize: 11, color: "#555", textAlign: "center" }}>
                  Please confirm all items above to enable download.
                </div>
              )}
            </div>
          )}
        </div>
      </div>

      {/* Waveform keyframe animations */}
      <style>{`
        @keyframes waveBar0 { 0%{height:15%} 100%{height:85%} }
        @keyframes waveBar1 { 0%{height:35%} 100%{height:65%} }
        @keyframes waveBar2 { 0%{height:20%} 100%{height:100%} }
        @keyframes waveBar3 { 0%{height:55%} 100%{height:35%} }
        @keyframes waveBar4 { 0%{height:28%} 100%{height:75%} }
      `}</style>
    </div>
  );
}
