import { Router, type IRouter } from "express";
import authRouter from "./auth";
import webauthnLoginRouter from "./webauthnLogin";
import healthRouter from "./health";
import notificationsRouter from "./notifications";
import feedbackRouter from "./feedback";
import adminRouter from "./admin";
import adminAiRouter from "./admin-ai";
import chatRouter from "./chat";
import aiRouter from "./ai";
import generatedDocumentsRouter from "./generated-documents";
import userRouter from "./user";
import knowledgeRouter from "./knowledge";
import stripeRouter from "./stripe";
import casesRouter from "./cases";
import securityRouter from "./security";
import ifpRouter from "./ifp";
import exhibitRouter from "./exhibit";
import tutorRouter from "./tutor";

const router: IRouter = Router();

router.use(authRouter);
router.use(webauthnLoginRouter);
router.use(healthRouter);
router.use(notificationsRouter);
router.use(feedbackRouter);
router.use(adminRouter);
router.use(adminAiRouter);
router.use(chatRouter);
router.use(aiRouter);
router.use(generatedDocumentsRouter);
router.use(userRouter);
router.use(knowledgeRouter);
router.use(stripeRouter);
router.use(casesRouter);
router.use(securityRouter);
router.use(ifpRouter);
router.use(exhibitRouter);
router.use(tutorRouter);

export default router;
